name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Pre-fetch jolokia 1.6.2
      run: mvn -B mvn dependency:get -Dartifact=org.jolokia:jolokia-war-unsecured:1.6.2:war
    - name: Build with Maven
      run: mvn -B verify
